name = "celal-site"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

# Environment variables
[env.production.vars]
SITE_URL = "https://celalbasaran.com"
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-jwt-key-production"

# Production KV Namespaces
[[env.production.kv_namespaces]]
binding = "SITE_DATA"
id = "celalbasaran-site-data"

[[env.production.kv_namespaces]]
binding = "ADMIN_DATA"
id = "celalbasaran-admin-data"

# Production R2 Buckets
[[env.production.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "celalbasaran-media"

[env.preview.vars]
SITE_URL = "https://preview.celalbasaran.com"
ENVIRONMENT = "preview"
JWT_SECRET = "your-super-secret-jwt-key-preview"

# Preview KV Namespaces
[[env.preview.kv_namespaces]]
binding = "SITE_DATA"
preview_id = "celalbasaran-site-data-preview"

[[env.preview.kv_namespaces]]
binding = "ADMIN_DATA"
preview_id = "celalbasaran-admin-data-preview"

# Preview R2 Buckets
[[env.preview.r2_buckets]]
binding = "MEDIA_BUCKET"
preview_bucket_name = "celalbasaran-media-preview" 