name = "celal-site"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

# Environment variables
[env.production.vars]
SITE_URL = "https://celalbasaran.com"
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-jwt-key-production"

[env.preview.vars]
SITE_URL = "https://preview.celalbasaran.com"
ENVIRONMENT = "preview"
JWT_SECRET = "your-super-secret-jwt-key-preview"

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "SITE_DATA"
id = "celalbasaran-site-data"
preview_id = "celalbasaran-site-data-preview"

[[kv_namespaces]]
binding = "ADMIN_DATA"
id = "celalbasaran-admin-data"
preview_id = "celalbasaran-admin-data-preview"

# R2 Object Storage for file uploads
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "celalbasaran-media"
preview_bucket_name = "celalbasaran-media-preview" 