name = "celal-site"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

# Environment variables
[env.production]
routes = [
  { pattern = "celalbasaran.com/*", zone_name = "celalbasaran.com" }
]

[env.production.vars]
SITE_URL = "https://celalbasaran.com"
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-jwt-key-production"

[env.preview.vars]
SITE_URL = "https://preview.celalbasaran.com"
ENVIRONMENT = "preview"

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "SITE_DATA"
id = "celalbasaran-site-data"
preview_id = "celalbasaran-site-data-preview"

[[kv_namespaces]]
binding = "ADMIN_DATA"
id = "celalbasaran-admin-data"
preview_id = "celalbasaran-admin-data-preview"

[env.development]
vars = { 
  ENVIRONMENT = "development",
  JWT_SECRET = "your-super-secret-jwt-key-development"
}

[[env.production.d1_databases]]
binding = "DB"
database_name = "celal-site-production"
database_id = "your-database-id"

[[env.development.d1_databases]]
binding = "DB"
database_name = "celal-site-development"
database_id = "your-dev-database-id"

[build]
command = "npm run build"
cwd = "."
watch_dir = "functions" 