name = "celal-site"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

# Default KV Namespaces for development
[[kv_namespaces]]
binding = "SITE_DATA"
id = "aa74f8e3bbab466e94f14bcc0bf0b5e2"

[[kv_namespaces]]
binding = "ADMIN_DATA"
id = "c445a17e3d3846609c2516e35aaf8573"

# Environment variables
[env.production.vars]
SITE_URL = "https://celalbasaran.com"
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-jwt-key-production"

# Production KV Namespaces
[[env.production.kv_namespaces]]
binding = "SITE_DATA"
id = "aa74f8e3bbab466e94f14bcc0bf0b5e2"

[[env.production.kv_namespaces]]
binding = "ADMIN_DATA"
id = "c445a17e3d3846609c2516e35aaf8573"

# Production R2 Buckets
# [[env.production.r2_buckets]]
# binding = "MEDIA_BUCKET"
# bucket_name = "celalbasaran-media"

[env.preview.vars]
SITE_URL = "https://preview.celalbasaran.com"
ENVIRONMENT = "preview"
JWT_SECRET = "your-super-secret-jwt-key-preview"

# Preview KV Namespaces
[[env.preview.kv_namespaces]]
binding = "SITE_DATA"
id = "aa74f8e3bbab466e94f14bcc0bf0b5e2"

[[env.preview.kv_namespaces]]
binding = "ADMIN_DATA"
id = "c445a17e3d3846609c2516e35aaf8573"

# Preview R2 Buckets
# [[env.preview.r2_buckets]]
# binding = "MEDIA_BUCKET"
# preview_bucket_name = "celalbasaran-media-preview" 